spring:
  data:
    mongodb:
      port: 27017
      database: pokemon-service
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus